name: Dataflow flex template example
on: push

jobs:
  build-flex-template:
    name: Build the Dataflow flex template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build step
        env:
          IMAGE_NAME: samples/dataflow/streaming-beam
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GKE_KEY }}
        id: kubeflow
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GKE_KEY}}
          IMAGE_TAG:  gcr.io/${{ secrets.GCP_PROJECT }}/${{env.IMAGE_NAME}}:121413313
          DOCKERIMAGE_PATH: example/.
          TEMPLATE_PATH: gs://${{ secrets.GCP_BUCKET }}/dataflow/templates/streaming-beam.json
          METADATA_PATH: example/metadata.json
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          
          
          # .github/workflows/deploy.yml
name: Deploy dataflow
on: push
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  APP_ID: continuous-deployment
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
jobs:
  deploy:
    name: Deploy to dataflow
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
